// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: proto/db.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DbClient is the client API for Db service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DbClient interface {
	IsUserAuthorized(ctx context.Context, in *UserAuthInfo, opts ...grpc.CallOption) (*UserAuthResponse, error)
	GetUserMovieList(ctx context.Context, in *ID, opts ...grpc.CallOption) (*MovieList, error)
	GetMovieStats(ctx context.Context, in *ID, opts ...grpc.CallOption) (*MovieStats, error)
}

type dbClient struct {
	cc grpc.ClientConnInterface
}

func NewDbClient(cc grpc.ClientConnInterface) DbClient {
	return &dbClient{cc}
}

func (c *dbClient) IsUserAuthorized(ctx context.Context, in *UserAuthInfo, opts ...grpc.CallOption) (*UserAuthResponse, error) {
	out := new(UserAuthResponse)
	err := c.cc.Invoke(ctx, "/db.proto.Db/IsUserAuthorized", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbClient) GetUserMovieList(ctx context.Context, in *ID, opts ...grpc.CallOption) (*MovieList, error) {
	out := new(MovieList)
	err := c.cc.Invoke(ctx, "/db.proto.Db/GetUserMovieList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbClient) GetMovieStats(ctx context.Context, in *ID, opts ...grpc.CallOption) (*MovieStats, error) {
	out := new(MovieStats)
	err := c.cc.Invoke(ctx, "/db.proto.Db/GetMovieStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DbServer is the server API for Db service.
// All implementations must embed UnimplementedDbServer
// for forward compatibility
type DbServer interface {
	IsUserAuthorized(context.Context, *UserAuthInfo) (*UserAuthResponse, error)
	GetUserMovieList(context.Context, *ID) (*MovieList, error)
	GetMovieStats(context.Context, *ID) (*MovieStats, error)
	mustEmbedUnimplementedDbServer()
}

// UnimplementedDbServer must be embedded to have forward compatible implementations.
type UnimplementedDbServer struct {
}

func (UnimplementedDbServer) IsUserAuthorized(context.Context, *UserAuthInfo) (*UserAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsUserAuthorized not implemented")
}
func (UnimplementedDbServer) GetUserMovieList(context.Context, *ID) (*MovieList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserMovieList not implemented")
}
func (UnimplementedDbServer) GetMovieStats(context.Context, *ID) (*MovieStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMovieStats not implemented")
}
func (UnimplementedDbServer) mustEmbedUnimplementedDbServer() {}

// UnsafeDbServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DbServer will
// result in compilation errors.
type UnsafeDbServer interface {
	mustEmbedUnimplementedDbServer()
}

func RegisterDbServer(s grpc.ServiceRegistrar, srv DbServer) {
	s.RegisterService(&Db_ServiceDesc, srv)
}

func _Db_IsUserAuthorized_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAuthInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServer).IsUserAuthorized(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/db.proto.Db/IsUserAuthorized",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServer).IsUserAuthorized(ctx, req.(*UserAuthInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Db_GetUserMovieList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServer).GetUserMovieList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/db.proto.Db/GetUserMovieList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServer).GetUserMovieList(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Db_GetMovieStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServer).GetMovieStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/db.proto.Db/GetMovieStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServer).GetMovieStats(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

// Db_ServiceDesc is the grpc.ServiceDesc for Db service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Db_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "db.proto.Db",
	HandlerType: (*DbServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsUserAuthorized",
			Handler:    _Db_IsUserAuthorized_Handler,
		},
		{
			MethodName: "GetUserMovieList",
			Handler:    _Db_GetUserMovieList_Handler,
		},
		{
			MethodName: "GetMovieStats",
			Handler:    _Db_GetMovieStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/db.proto",
}
